# Generated by Django 5.1.1 on 2024-09-05 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commercial_Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14)),
                ('adress', models.CharField(max_length=100)),
                ('phone', models.IntegerField(max_length=14)),
                ('car_parking_spaces', models.IntegerField(max_length=100)),
                ('motorcycle_parking_spaces', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('car_plate', models.CharField(max_length=7)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
    ]
