# Generated by Django 5.1.1 on 2024-09-05 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercial_establishment',
            name='car_parking_spaces',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='commercial_establishment',
            name='motorcycle_parking_spaces',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='commercial_establishment',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='car_plate',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
